pub fn latin_to_elder_futhark(string: &str) -> String {
    string
        .replace("ae", "ᛇ")
        .replace("ng", "ᛜ")
        .replace("th", "ᚦ")
        .replace("a", "ᚨ")
        .replace("b", "ᛒ")
        .replace("c", "ᚲ")
        .replace("d", "ᛞ")
        .replace("e", "ᛖ")
        .replace("f", "ᚠ")
        .replace("g", "ᚷ")
        .replace("h", "ᚺ")
        .replace("i", "ᛁ")
        .replace("j", "ᛃ")
        .replace("k", "ᚲ")
        .replace("l", "ᛚ")
        .replace("m", "ᛗ")
        .replace("n", "ᚾ")
        .replace("o", "ᛟ")
        .replace("p", "ᛈ")
        .replace("q", "ᚲ")
        .replace("r", "ᚱ")
        .replace("s", "ᛊ")
        .replace("t", "ᛏ")
        .replace("u", "ᚢ")
        .replace("v", "ᚢ")
        .replace("w", "ᚹ")
        .replace("y", "ᛉ")
}
